version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: fintrack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fintrack_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - fintrack-pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fintrack-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fintrack.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  fintrack-pgdata:
